[project]
name = "nanovlm"
version = "0.1.0"
description = "nanovlm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.0",
    "datasets>=4.0.0",
    "huggingface-hub>=0.34.4",
    "openai>=1.65.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "sentencepiece>=0.2.0",
    "termcolor>=2.5.0",
    "torch>=2.8.0",
    "transformers>=4.55.0",
]

[tool.setuptools]
py-modules = []

